### ISSUE TITLE
submitting payment issue

### ISSUE THREAD

**Issue by sj973** [Zenyrax/TuneBot#1]
402 error 
![error](https://github.com/Zenyrax/TuneBot/assets/134250236/088f4ff8-8e51-48de-bff2-0de7ceceaf5c)

**Comment by Zenyrax** [comment]
Hi! This is an issue with Stripe rejecting your card information. Please make sure there are no unnecessary spaces and that your expiration month and year only have two characters (ex. 04 and 29 instead of 4 and 2029). I've pushed an update that has more descript logging of this payment issue, so you can see exactly why it's failing. Thank you for bringing this to my attention. :)

**Comment by sj973** [comment]
No spaces I quadrupled check. Thought it might’ve been a Amex issue and switch to cap1 and same thing.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sj973** [comment]
I am also testing with a oos item could that be the case for the error?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Zenyrax** [comment]
> No spaces I quadrupled check. Thought it might’ve been a Amex issue and switch to cap1 and same thing.

It's likely not the OOS item. Do you mind running the new version and seeing what error Stripe is giving you? Also, can you tell me what site you're running? There could be an issue with parsing the Stripe API key.

**Comment by sj973** [comment]
Request error while creating payment token [your card was declined. Your request was in live mode, but used a known test card.] (402)

I am running drmusic123.com

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sj973** [comment]
Also not allowing me to paste webhook

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sj973** [comment]
its adding the oos item to cart and selecting shipping method and in the github description it says it will keep trying to cart.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Zenyrax** [comment]
> Also not allowing me to paste webhook

Sometimes you have to right-click on the window to paste. I'll make a note of that in the UI in the next version.

**Comment by Zenyrax** [comment]
> its adding the oos item to cart and selecting shipping method and in the github description it says it will keep trying to cart. 

It should only get that far if it successfully added the item to the cart. Are you sure the product isn't restocking? I'm running for restocks for an OOS vinyl on that site, and it's working as intended.

**Comment by sj973** [comment]
Yea it not restocking it’s oos. I’m pretty sure I’m doing everything right. Tried 4 different cc also

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sj973** [comment]
[cid:7b6bf923-e78d-4097-9eef-2eaffe99264a]
________________________________
